name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    env:
      FOLDER_PATH: /${{ secrets.FOLDER_PATH }}
      DEPLOY_ON_SERVER: ${{ secrets.DEPLOY_ON_SERVER }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag viethung512/basic-frontend:$GITHUB_SHA
      
    - name: Login to dockerhub
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to dockerhub
      run: docker push viethung512/basic-frontend:$GITHUB_SHA

    # Incase need deploy to server
    - name: Setup SSH to server
      uses: garygrossgarten/github-action-ssh@release
      if: ${{ env.DEPLOY_ON_SERVER == 'true' }}
      with:
        command: "
          cd ${{ env.FOLDER_PATH }} &&
          grep -v 'FRONTEND_IMAGE_TAG' .env > temp && mv temp .env &&
          echo '\nFRONTEND_IMAGE_TAG=${{ github.sha }}' >> .env &&
          cd ${{ env.FOLDER_PATH }} &&
          sudo docker-compose pull && sudo docker-compose up -d
        "
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.PRIVATE_KEY }}

# rm -rf .env && touch .env && echo ${{ secrets.ENV_CONTENT }} >> .env &&